Contenerizing + Deployment pipeline

diff --git a/.github/workflows/commit-stage.yml b/.github/workflows/commit-stage.yml
--- a/.github/workflows/commit-stage.yml
+++ b/.github/workflows/commit-stage.yml
@@ -1,6 +1,11 @@
 name: Commit Stage
 on: push
 
+#env:
+#  REGISTRY: ghcr.io
+#  IMAGE_NAME: p0m.p0m@outlook.fr/catalog-service
+#  VERSION: latest
+
 jobs:
   build:
     name: Build and Test
@@ -24,14 +29,60 @@ jobs:
           path: "${{ github.workspace }}"
           fail-build: false
           severity-cutoff: high
-#         acs-report-enable: true				
-#      - name: Upload vulnerability report			# Public repo or Pro account only
+         acs-report-enable: true
+      - name: Upload vulnerability report			# Public repo or Pro account only
+        uses: github/codeql-action/upload-sarif@v2
+        if: success() || failure()
+        with:
+          sarif_file: ${{ steps.scan.outputs.sarif }}
+      - name: Build, unit tests and integration tests
+        run: |
+          cd Chapter06/catalog-service
+          chmod +x gradlew
+          ./gradlew build
+
+#  package:
+#    name: Package and Publish
+#    if: ${{ github.ref == 'refs/heads/main' }}
+#    needs: [ build ]
+#    runs-on: ubuntu-22.04
+#    permissions:
+#      contents: read
+#      packages: write
+#      security-events: write
+#    steps:
+#      - name: Checkout source code
+#        uses: actions/checkout@v3
+#      - name: Set up JDK
+#        uses: actions/setup-java@v3
+#        with:
+#          distribution: temurin
+#          java-version: 17
+#          cache: gradle
+#      - name: Build container image
+#        run: |
+#          cd Chapter06/catalog-service
+#          chmod +x gradlew
+#          ./gradlew bootBuildImage \
+#            --imageName ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+#      - name: OCI image vulnerability scanning
+#        uses: anchore/scan-action@v3
+#        id: scan
+#        with:
+#          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+#          fail-build: false
+#          severity-cutoff: high
+#          acs-report-enable: true
+#      - name: Upload vulnerability report
 #        uses: github/codeql-action/upload-sarif@v2
 #        if: success() || failure()
 #        with:
 #          sarif_file: ${{ steps.scan.outputs.sarif }}
-      - name: Build, unit tests and integration tests
-        run: |
-          cd Chapter03/catalog-service
-          chmod +x gradlew
-          ./gradlew build
+#      - name: Log into container registry
+#        uses: docker/login-action@v2
+#        with:
+#          registry: ${{ env.REGISTRY }}
+#          username: ${{ github.actor }}
+#          password: ${{ secrets.GITHUB_TOKEN }}
+#      - name: Publish container image
+#        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
